# Generated by Django 5.2.3 on 2025-06-15 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('starting_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ending_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=10)),
                ('timeline_type', models.CharField(choices=[('FIXED_DATE', 'Fixed Date'), ('DURATION', 'Duration')], max_length=20)),
                ('timeline_fixed_date', models.DateField(blank=True, null=True)),
                ('timeline_duration_start', models.DateField(blank=True, null=True)),
                ('timeline_duration_end', models.DateField(blank=True, null=True)),
                ('image', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=100)),
                ('paymentmethod', models.CharField(blank=True, max_length=50, null=True)),
                ('paymentmethodaccount', models.CharField(blank=True, max_length=100, null=True)),
                ('bio', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('biddingAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('biddingCurrency', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('opened', 'Opened'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='opened', max_length=10)),
                ('gigId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='GigGh.gig')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('submissionFile', models.TextField()),
                ('submissionNotes', models.TextField(blank=True)),
                ('bidId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='GigGh.bid')),
                ('gigId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='GigGh.gig')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('submissionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='GigGh.submission')),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_received', to='GigGh.user')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_made', to='GigGh.user')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('room', models.CharField(max_length=100)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_received', to='GigGh.user')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_sent', to='GigGh.user')),
            ],
        ),
    ]
