# Generated by Django 5.2.3 on 2025-06-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GigGh', '0002_user_phone_number_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='category',
            field=models.CharField(choices=[('design', 'Design'), ('development', 'Development'), ('writing', 'Writing'), ('administrative', 'Administrative')], default='development', max_length=15),
        ),
    ]
