# Generated by Django 5.2.3 on 2025-07-30 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GigGh', '0004_alter_bid_freelancer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='timeline_type',
            field=models.CharField(choices=[('FIXED_DATE', 'Fixed_Date'), ('DURATION', 'Duration')], max_length=20),
        ),
    ]
