# Generated by Django 5.2.3 on 2025-07-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GigGh', '0005_alter_gig_timeline_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='timeline_type',
            field=models.CharField(choices=[('fixed_date', 'Fixed Date'), ('duration', 'Duration')], max_length=20),
        ),
    ]
