# Generated by Django 5.2.3 on 2025-07-30 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GigGh', '0006_alter_gig_timeline_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gigs', to=settings.AUTH_USER_MODEL),
        ),
    ]
