# Generated by Django 5.2.3 on 2025-08-02 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GigGh', '0007_alter_gig_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('canceled', 'Canceled')], default='pending', max_length=10),
        ),
    ]
