# Generated by Django 5.2.3 on 2025-08-02 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GigGh', '0008_alter_bid_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='bid_attachments/', verbose_name='Attachment'),
        ),
        migrations.AddField(
            model_name='bid',
            name='attachment_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
