# Generated by Django 5.2.3 on 2025-08-04 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GigGh', '0009_bid_attachment_bid_attachment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
