# Generated by Django 5.2.3 on 2025-08-04 14:18

from django.db import migrations

def clean_orphaned_bids(apps, schema_editor):
    Bid = apps.get_model('GigGh', 'Bid')
    Bid.objects.filter(gigId__isnull=True).delete()

class Migration(migrations.Migration):
    dependencies = [
        ('GigGh', '0010_bid_notes'),
    ]

    operations = [
        migrations.RunPython(clean_orphaned_bids),
    ]
