# Generated by Django 5.2.3 on 2025-08-06 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GigGh', '0011_clean_orphaned_bids'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['timestamp']},
        ),
        migrations.RemoveField(
            model_name='chat',
            name='room',
        ),
        migrations.AddField(
            model_name='chat',
            name='bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='GigGh.bid'),
        ),
        migrations.AddField(
            model_name='chat',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bid',
            name='gigId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bids', to='GigGh.gig'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='gig',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='GigGh.gig'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chat',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['gig', 'sender', 'recipient'], name='GigGh_chat_gig_id_d828b9_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['timestamp'], name='GigGh_chat_timesta_fb4811_idx'),
        ),
    ]
