# Generated by Django 5.2.3 on 2025-08-06 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GigGh', '0012_alter_chat_options_remove_chat_room_chat_bid_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chat',
            name='GigGh_chat_gig_id_d828b9_idx',
        ),
        migrations.RemoveIndex(
            model_name='chat',
            name='GigGh_chat_timesta_fb4811_idx',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='bid',
        ),
        migrations.AddField(
            model_name='chat',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chat',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chat',
            name='gig',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GigGh.gig'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chat',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
